version: "3.8"

services:
  mongo:
    build:
      context: ./mongo
    container_name: mongo
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://admin:${MONGO_ROOT_PASSWORD}@mongo:27017/stockdb?authSource=admin
      - JWT_SECRET=monSuperSecretChangeLe!
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["node", "index.js"]

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  mongo-data:

